# Generated by Django 3.2.13 on 2022-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('c_disc', models.TextField()),
                ('c_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
