# Generated by Django 3.2.13 on 2022-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_title', models.CharField(max_length=50)),
                ('g_disc', models.TextField()),
                ('g_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
