# Generated by Django 3.2.13 on 2022-06-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_image',
            field=models.ImageField(upload_to='assets/pics'),
        ),
    ]
