# Generated by Django 3.2.13 on 2022-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_gallery_g_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
